local PLUGIN = PLUGIN;

PLUGIN.voices = Clockwork.kernel:NewLibrary("CombineVoices");

PLUGIN.voices.stored = {
	combineVoices = {}
};

-- A function to add a Combine voice.
function PLUGIN.voices:AddCombine(faction, command, phrase, sound, female, menu)
	PLUGIN.voices.stored.combineVoices[#PLUGIN.voices.stored.combineVoices + 1] = {
		command = command,
		faction = faction,
		phrase = phrase,
		female = female,
		sound = sound,
		menu = menu
	};
end;

PLUGIN.voices:AddCombine("Combine", "Sweeping", "Sweeping for suspect.", "npc/metropolice/hiding02.wav");
PLUGIN.voices:AddCombine("Combine", "Isolate", "Isolate!", "npc/metropolice/hiding05.wav");
PLUGIN.voices:AddCombine("Combine", "You Can Go", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav");
PLUGIN.voices:AddCombine("Combine", "Need Assistance", "Eleven-ninety-nine, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav");
PLUGIN.voices:AddCombine("Combine", "Administer", "Administer.", "npc/metropolice/vo/administer.wav");
PLUGIN.voices:AddCombine("Combine", "Affirmative", "Affirmative.", "npc/metropolice/vo/affirmative.wav");
PLUGIN.voices:AddCombine("Combine", "All Units Move In", "All units move in!", "npc/metropolice/vo/allunitsmovein.wav");
PLUGIN.voices:AddCombine("Combine", "Amputate", "Amputate.", "npc/metropolice/vo/amputate.wav");
PLUGIN.voices:AddCombine("Combine", "Anti-Citizen", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav");
PLUGIN.voices:AddCombine("Combine", "Citizen", "Citizen.", "npc/metropolice/vo/citizen.wav");
PLUGIN.voices:AddCombine("Combine", "Copy", "Copy.", "npc/metropolice/vo/copy.wav");
PLUGIN.voices:AddCombine("Combine", "Cover Me", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav");
PLUGIN.voices:AddCombine("Combine", "Assist Trespass", "Assist for a criminal trespass!", "npc/metropolice/vo/criminaltrespass63.wav");
PLUGIN.voices:AddCombine("Combine", "Destroy Cover", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav");
PLUGIN.voices:AddCombine("Combine", "Dont Move", "Don't move!", "npc/metropolice/vo/dontmove.wav");
PLUGIN.voices:AddCombine("Combine", "Final Verdict", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav");
PLUGIN.voices:AddCombine("Combine", "Final Warning", "Final warning!", "npc/metropolice/vo/finalwarning.wav");
PLUGIN.voices:AddCombine("Combine", "First Warning", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav");
PLUGIN.voices:AddCombine("Combine", "Get Down", "Get down!", "npc/metropolice/vo/getdown.wav");
PLUGIN.voices:AddCombine("Combine", "Get Out", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav");
PLUGIN.voices:AddCombine("Combine", "Suspect One", "I got suspect one here.", "npc/metropolice/vo/gotsuspect1here.wav");
PLUGIN.voices:AddCombine("Combine", "Help", "Help!", "npc/metropolice/vo/help.wav");
PLUGIN.voices:AddCombine("Combine", "Running", "He's running!", "npc/metropolice/vo/hesrunning.wav");
PLUGIN.voices:AddCombine("Combine", "Hold It", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav");
PLUGIN.voices:AddCombine("Combine", "Move Along 2", "I said move along.", "npc/metropolice/vo/isaidmovealong.wav");
PLUGIN.voices:AddCombine("Combine", "Malcompliance", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav");
PLUGIN.voices:AddCombine("Combine", "Keep Moving", "Keep moving!", "npc/metropolice/vo/keepmoving.wav");
PLUGIN.voices:AddCombine("Combine", "Lock Position", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav");
PLUGIN.voices:AddCombine("Combine", "Trouble", "Lookin' for trouble?", "npc/metropolice/vo/lookingfortrouble.wav");
PLUGIN.voices:AddCombine("Combine", "Look Out", "Look out!", "npc/metropolice/vo/lookout.wav");
PLUGIN.voices:AddCombine("Combine", "Minor Hits", "Minor hits, continuing prosecution.", "npc/metropolice/vo/minorhitscontinuing.wav");
PLUGIN.voices:AddCombine("Combine", "Move", "Move!", "npc/metropolice/vo/move.wav");
PLUGIN.voices:AddCombine("Combine", "Move Along", "Move along!", "npc/metropolice/vo/movealong3.wav");
PLUGIN.voices:AddCombine("Combine", "Move Back", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav");
PLUGIN.voices:AddCombine("Combine", "Move It", "Move it!", "npc/metropolice/vo/moveit2.wav");
PLUGIN.voices:AddCombine("Combine", "Hardpoint", "Moving to hardpoint.", "npc/metropolice/vo/movingtohardpoint.wav");
PLUGIN.voices:AddCombine("Combine", "Officer Help", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav");
PLUGIN.voices:AddCombine("Combine", "Privacy", "Possible level three civil privacy violator here!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav");
PLUGIN.voices:AddCombine("Combine", "Judgement", "Suspect prepare to receive civil judgement!", "npc/metropolice/vo/prepareforjudgement.wav");
PLUGIN.voices:AddCombine("Combine", "Priority Two", "I have a priority two anti-citizen here.", "npc/metropolice/vo/priority2anticitizenhere.wav");
PLUGIN.voices:AddCombine("Combine", "Prosecute", "Prosecute!", "npc/metropolice/vo/prosecute.wav");
PLUGIN.voices:AddCombine("Combine", "Amputate Ready", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav");
PLUGIN.voices:AddCombine("Combine", "Rodger That", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav");
PLUGIN.voices:AddCombine("Combine", "Search", "Search!", "npc/metropolice/vo/search.wav");
PLUGIN.voices:AddCombine("Combine", "Shit", "Shit!", "npc/metropolice/vo/shit.wav");
PLUGIN.voices:AddCombine("Combine", "Sentence Delivered", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav");
PLUGIN.voices:AddCombine("Combine", "Sterilize", "Sterilize!", "npc/metropolice/vo/sterilize.wav");
PLUGIN.voices:AddCombine("Combine", "Take Cover", "Take cover!", "npc/metropolice/vo/takecover.wav");
PLUGIN.voices:AddCombine("Combine", "Restrict", "Restrict!", "npc/metropolice/vo/restrict.wav");
PLUGIN.voices:AddCombine("Combine", "Restricted", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav");
PLUGIN.voices:AddCombine("Combine", "Second Warning", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav");
PLUGIN.voices:AddCombine("Combine", "Verdict", "You want a non-compliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav");
PLUGIN.voices:AddCombine("Combine", "Backup", "Backup!", "npc/metropolice/vo/backup.wav");
PLUGIN.voices:AddCombine("Combine", "Apply", "Apply.", "npc/metropolice/vo/apply.wav");
PLUGIN.voices:AddCombine("Combine", "Restriction", "Terminal restriction zone.", "npc/metropolice/vo/terminalrestrictionzone.wav");
PLUGIN.voices:AddCombine("Combine", "Complete", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav");
PLUGIN.voices:AddCombine("Combine", "Location Unknown", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav");
PLUGIN.voices:AddCombine("Combine", "Can 1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav");
PLUGIN.voices:AddCombine("Combine", "Can 2", "Pick... up... the can.", "npc/metropolice/vo/pickupthecan2.wav");
PLUGIN.voices:AddCombine("Combine", "Wrap It", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav");
PLUGIN.voices:AddCombine("Combine", "Can 3", "I said pickup the can!", "npc/metropolice/vo/pickupthecan3.wav");
PLUGIN.voices:AddCombine("Combine", "Can 4", "Now, put it in the trash can.", "npc/metropolice/vo/putitinthetrash1.wav");
PLUGIN.voices:AddCombine("Combine", "Can 5", "I said put it in the trash can!", "npc/metropolice/vo/putitinthetrash2.wav");
PLUGIN.voices:AddCombine("Combine", "Now Get Out", "Now get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav");
PLUGIN.voices:AddCombine("Combine", "Haha", "Haha.", "npc/metropolice/vo/chuckle.wav");
PLUGIN.voices:AddCombine("Combine", "X-Ray", "X-Ray!", "npc/metropolice/vo/xray.wav");
PLUGIN.voices:AddCombine("Combine", "Patrol", "Patrol!", "npc/metropolice/vo/patrol.wav");
PLUGIN.voices:AddCombine("Combine", "Serve", "Serve.", "npc/metropolice/vo/serve.wav");
PLUGIN.voices:AddCombine("Combine", "Knocked Over", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav");
PLUGIN.voices:AddCombine("Combine", "Watch It", "Watch it!", "npc/metropolice/vo/watchit.wav");
PLUGIN.voices:AddCombine("Combine", "Restricted Canals", "Suspect is using restricted canals at...", "npc/metropolice/vo/suspectusingrestrictedcanals.wav");
PLUGIN.voices:AddCombine("Combine", "505", "Subject is five-oh-five!", "npc/metropolice/vo/subjectis505.wav");
PLUGIN.voices:AddCombine("Combine", "404", "Possible 404 here!", "npc/metropolice/vo/possible404here.wav");
PLUGIN.voices:AddCombine("Combine", "Vacate", "Vacate citizen!", "npc/metropolice/vo/vacatecitizen.wav");
PLUGIN.voices:AddCombine("Combine", "Escapee", "Priority two escapee.", "npc/combine_soldier/vo/prioritytwoescapee.wav");
PLUGIN.voices:AddCombine("Combine", "Objective", "Priority one objective.", "npc/combine_soldier/vo/priority1objective.wav");
PLUGIN.voices:AddCombine("Combine", "Payback", "Payback.", "npc/combine_soldier/vo/payback.wav");
PLUGIN.voices:AddCombine("Combine", "Got Him Now", "Affirmative, we got him now.", "npc/combine_soldier/vo/affirmativewegothimnow.wav");
PLUGIN.voices:AddCombine("Combine", "Antiseptic", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav");
PLUGIN.voices:AddCombine("Combine", "Cleaned", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav");
PLUGIN.voices:AddCombine("Combine", "Cleanup", "Engaged in cleanup.", "npc/combine_soldier/vo/engagedincleanup.wav");
PLUGIN.voices:AddCombine("Combine", "Engaging", "Engaging.", "npc/combine_soldier/vo/engaging.wav");
PLUGIN.voices:AddCombine("Combine", "Full Response", "Executing full response.", "npc/combine_soldier/vo/executingfullresponse.wav");
PLUGIN.voices:AddCombine("Combine", "Heavy Resistance", "Overwatch advise, we have heavy resistance.", "npc/combine_soldier/vo/heavyresistance.wav");
PLUGIN.voices:AddCombine("Combine", "Inbound", "Inbound.", "npc/combine_soldier/vo/inbound.wav");
PLUGIN.voices:AddCombine("Combine", "Lost Contact", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav");
PLUGIN.voices:AddCombine("Combine", "Move In", "Move in!", "npc/combine_soldier/vo/movein.wav");
PLUGIN.voices:AddCombine("Combine", "Harden Position", "Harden that position!", "npc/combine_soldier/vo/hardenthatposition.wav");
PLUGIN.voices:AddCombine("Combine", "Go Sharp", "Go sharp, go sharp!", "npc/combine_soldier/vo/gosharpgosharp.wav");
PLUGIN.voices:AddCombine("Combine", "Delivered", "Delivered.", "npc/combine_soldier/vo/delivered.wav");
PLUGIN.voices:AddCombine("Combine", "Necrotics Inbound", "Necrotics, inbound!", "npc/combine_soldier/vo/necroticsinbound.wav");
PLUGIN.voices:AddCombine("Combine", "Necrotics", "Necrotics.", "npc/combine_soldier/vo/necrotics.wav");
PLUGIN.voices:AddCombine("Combine", "Outbreak", "Outbreak!", "npc/combine_soldier/vo/outbreak.wav");
PLUGIN.voices:AddCombine("Combine", "Copy That", "Copy that.", "npc/combine_soldier/vo/copythat.wav");
PLUGIN.voices:AddCombine("Combine", "Outbreak Status", "Outbreak status is code.", "npc/combine_soldier/vo/outbreakstatusiscode.wav");
PLUGIN.voices:AddCombine("Combine", "Overwatch", "Overwatch!", "npc/combine_soldier/vo/overwatch.wav");
PLUGIN.voices:AddCombine("Combine", "Preserve", "Preserve!", "npc/metropolice/vo/preserve.wav");
PLUGIN.voices:AddCombine("Combine", "Pressure", "Pressure!", "npc/metropolice/vo/pressure.wav");
PLUGIN.voices:AddCombine("Combine", "Phantom", "Phantom!", "npc/combine_soldier/vo/phantom.wav");
PLUGIN.voices:AddCombine("Combine", "Stinger", "Stinger!", "npc/combine_soldier/vo/stinger.wav");
PLUGIN.voices:AddCombine("Combine", "Shadow", "Shadow!", "npc/combine_soldier/vo/shadow.wav");
PLUGIN.voices:AddCombine("Combine", "Savage", "Savage!", "npc/combine_soldier/vo/savage.wav");
PLUGIN.voices:AddCombine("Combine", "Reaper", "Reaper!", "npc/combine_soldier/vo/reaper.wav");
PLUGIN.voices:AddCombine("Combine", "Victor", "Victor!", "npc/metropolice/vo/victor.wav");
PLUGIN.voices:AddCombine("Combine", "Sector", "Sector!", "npc/metropolice/vo/sector.wav");
PLUGIN.voices:AddCombine("Combine", "Inject", "Inject!", "npc/metropolice/vo/inject.wav");
PLUGIN.voices:AddCombine("Combine", "Dagger", "Dagger!", "npc/combine_soldier/vo/dagger.wav");
PLUGIN.voices:AddCombine("Combine", "Blade", "Blade!", "npc/combine_soldier/vo/blade.wav");
PLUGIN.voices:AddCombine("Combine", "Razor", "Razor!", "npc/combine_soldier/vo/razor.wav");
PLUGIN.voices:AddCombine("Combine", "Nomad", "Nomad!", "npc/combine_soldier/vo/nomad.wav");
PLUGIN.voices:AddCombine("Combine", "Judge", "Judge!", "npc/combine_soldier/vo/judge.wav");
PLUGIN.voices:AddCombine("Combine", "Ghost", "Ghost!", "npc/combine_soldier/vo/ghost.wav");
PLUGIN.voices:AddCombine("Combine", "Sword", "Sword!", "npc/combine_soldier/vo/sword.wav");
PLUGIN.voices:AddCombine("Combine", "Union", "Union!", "npc/metropolice/vo/union.wav");
PLUGIN.voices:AddCombine("Combine", "Helix", "Helix!", "npc/combine_soldier/vo/helix.wav");
PLUGIN.voices:AddCombine("Combine", "Storm", "Storm!", "npc/combine_soldier/vo/storm.wav");
PLUGIN.voices:AddCombine("Combine", "Spear", "Spear!", "npc/combine_soldier/vo/spear.wav");
PLUGIN.voices:AddCombine("Combine", "Vamp", "Vamp!", "npc/combine_soldier/vo/vamp.wav");
PLUGIN.voices:AddCombine("Combine", "Nova", "Nova!", "npc/combine_soldier/vo/nova.wav");
PLUGIN.voices:AddCombine("Combine", "Mace", "Mace!", "npc/combine_soldier/vo/mace.wav");
PLUGIN.voices:AddCombine("Combine", "Grid", "Grid!", "npc/combine_soldier/vo/grid.wav");
PLUGIN.voices:AddCombine("Combine", "Kilo", "Kilo!", "npc/combine_soldier/vo/kilo.wav");
PLUGIN.voices:AddCombine("Combine", "Echo", "Echo!", "npc/combine_soldier/vo/echo.wav");
PLUGIN.voices:AddCombine("Combine", "Dash", "Dash!", "npc/combine_soldier/vo/dash.wav");
PLUGIN.voices:AddCombine("Combine", "Apex", "Apex!", "npc/combine_soldier/vo/apex.wav");
PLUGIN.voices:AddCombine("Combine", "Jury", "Jury!", "npc/metropolice/vo/jury.wav");
PLUGIN.voices:AddCombine("Combine", "King", "King!", "npc/metropolice/vo/king.wav");
PLUGIN.voices:AddCombine("Combine", "Lock", "Lock!", "npc/metropolice/vo/lock.wav");
PLUGIN.voices:AddCombine("Combine", "Vice", "Vice!", "npc/metropolice/vo/vice.wav");
PLUGIN.voices:AddCombine("Combine", "Zero", "Zero!", "npc/metropolice/vo/zero.wav");
PLUGIN.voices:AddCombine("Combine", "0", "Zero.", "npc/combine_soldier/vo/zero.wav");
PLUGIN.voices:AddCombine("Combine", "Zone", "Zone!", "npc/metropolice/vo/zone.wav");
PLUGIN.voices:AddCombine("Combine", "Code 7", "Code 7.", "npc/metropolice/vo/code7.wav");
PLUGIN.voices:AddCombine("Combine", "A 10-30", "I have a 10-30 at my 10-20, responding code 2.", "npc/metropolice/vo/ihave10-30my10-20responding.wav");
PLUGIN.voices:AddCombine("Combine", "Malcompliant 10-107", "Malcompliant 10-107 at my 10-20, preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav");
PLUGIN.voices:AddCombine("Combine", "Officer code 3", "Officer down! Code 3 to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20");
PLUGIN.voices:AddCombine("Combine", "A grenade", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav");
PLUGIN.voices:AddCombine("Combine", "10-8s", "10-8, standing by.", "npc/metropolice/vo/ten8standingby.wav");
PLUGIN.voices:AddCombine("Combine", "Is 10-8", "Unit is 10-8, standing by.", "npc/metropolice/vo/unitis10-8standingby.wav");
PLUGIN.voices:AddCombine("Combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav");
PLUGIN.voices:AddCombine("Combine", "Standing by.", "Standing by.", "npc/combine_soldier/vo/standingby].wav");
PLUGIN.voices:AddCombine("Combine", "Moved now", "Suspect has moved now to..", "npc/metropolice/vo/suspecthasmovednowto.wav");
PLUGIN.voices:AddCombine("Combine", "Ready to go", "Is ready to go!", "npc/metropolice/vo/isreadytogo.wav");
PLUGIN.voices:AddCombine("Combine", "Bouncer", "Bouncer, bouncer!", "npc/combine_soldier/vo/bouncerbouncer.wav");
PLUGIN.voices:AddCombine("Combine", "Standard Check", "Uhh..rodger that. Little uh..standard loyalty check procedure 243 my 10-22 intake station, over.", "npc/metropolice/vo/standardloyaltycheck.wav");
PLUGIN.voices:AddCombine("Combine", "Begin scanning", "10-0, begin scanning.", "npc/overwatch/radiovoice/beginscanning10-0.wav");
PLUGIN.voices:AddCombine("Combine", "Complete sentencing", "All protection team units, complete sentencing at will.", "npc/overwatch/radiovoice/completesentencingatwill.wav");
PLUGIN.voices:AddCombine("Combine", "Reinforcement teams", "Reinforcement teams code 3.", "npc/overwatch/radiovoice/reinforcementteamscode3.wav");
PLUGIN.voices:AddCombine("Combine", "Report status", "Local CP teams report status.", "npc/metropolice/vo/localcptreportstatus.wav");
PLUGIN.voices:AddCombine("Combine", "Closing", "Officer closing on suspect.", "npc/overwatch/radiovoice/officerclosingonsuspect.wav");
PLUGIN.voices:AddCombine("Combine", "Investigate and report", "Investigate and report.", "npc/overwatch/radiovoice/investigateandreport.wav");
PLUGIN.voices:AddCombine("Combine", "Amputation", "Immediate amputation.", "npc/overwatch/radiovoice/immediateamputation.wav");
PLUGIN.voices:AddCombine("Combine", "Forward pressure", "All units apply forward pressure.", "npc/overwatch/radiovoice/allunitsapplyforwardpressure.wav");
PLUGIN.voices:AddCombine("Combine", "243 suspect", "All units report status on 243 suspect.", "npc/overwatch/radiovoice/statuson243suspect.wav");
PLUGIN.voices:AddCombine("Combine", "BOL suspect", "All units BOL for 243 suspect.", "npc/overwatch/radiovoice/allunitsbolfor243suspect.wav");
PLUGIN.voices:AddCombine("Combine", "Respond", "Respond.", "npc/overwatch/radiovoice/respond.wav");
PLUGIN.voices:AddCombine("Combine", "Sterilization", "All units begin witness sterilization.", "npc/overwatch/radiovoice/allunitsbeginwhitnesssterilization.wav");
PLUGIN.voices:AddCombine("Combine", "Contain", "Remaining units contain.", "npc/overwatch/radiovoice/remainingunitscontain.wav");
PLUGIN.voices:AddCombine("Combine", "Report please", "Report please.", "npc/overwatch/radiovoice/reportplease.wav");
PLUGIN.voices:AddCombine("Combine", "Stabilization", "Socio-stabilization restored.", "npc/overwatch/radiovoice/sociostabilizationrestored.wav");
PLUGIN.voices:AddCombine("Combine", "Charged with", "Attention, you have been charged with:", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav");
PLUGIN.voices:AddCombine("Combine", "Final sentencing", "Prepare for final sentencing.", "npc/overwatch/radiovoice/prepareforfinalsentencing.wav");
PLUGIN.voices:AddCombine("Combine", "Receive verdict", "Prepare to receive verdict.", "npc/overwatch/radiovoice/preparetoreceiveverdict.wav");
PLUGIN.voices:AddCombine("Combine", "Judged guilty", "You are judged guilty by Civil Protection teams.", "npc/overwatch/radiovoice/youarejudgedguilty.wav");
PLUGIN.voices:AddCombine("Combine", "Capital malcompliance", "Capital malcompliance.", "npc/overwatch/radiovoice/capitalmalcompliance.wav");
PLUGIN.voices:AddCombine("Combine", "Level 5", "Level 5 anti-civil activity.", "npc/overwatch/radiovoice/level5anticivilactivity.wav");
PLUGIN.voices:AddCombine("Combine", "95", "95, illegal carrying.", "npc/overwatch/radiovoice/illegalcarrying95.wav");
PLUGIN.voices:AddCombine("Combine", "69", "69, posession of resources.", "npc/overwatch/radiovoice/posession69.wav");
PLUGIN.voices:AddCombine("Combine", "Unrest", "Promoting communal unrest.", "npc/overwatch/radiovoice/promotingcommunalunrest.wav");
PLUGIN.voices:AddCombine("Combine", "603", "603, unlawful entry.", "npc/overwatch/radiovoice/unlawfulentry603.wav");
PLUGIN.voices:AddCombine("Combine", "94", "94, weapon.", "npc/overwatch/radiovoice/weapon94.wav");
PLUGIN.voices:AddCombine("Combine", "Civic trust", "Violation of civic trust.", "npc/overwatch/radiovoice/violationofcivictrust.wav");
PLUGIN.voices:AddCombine("Combine", "51", "51b, threat to property.", "npc/overwatch/radiovoice/threattoproperty51b.wav");
PLUGIN.voices:AddCombine("Combine", "103", "10-103m, disturbance by mentally unfit.", "npc/overwatch/radiovoice/disturbancemental10-103m.wav");
PLUGIN.voices:AddCombine("Combine", "243", "243, assault on protection team.", "npc/overwatch/radiovoice/assault243.wav");
PLUGIN.voices:AddCombine("Combine", "27", "27, attempted crime.", "npc/overwatch/radiovoice/attemptedcrime27.wav");
PLUGIN.voices:AddCombine("Combine", "63", "63, criminal trespass.", "npc/overwatch/radiovoice/criminaltrespass63.wav");
PLUGIN.voices:AddCombine("Combine", "51", "51, non-sanctioned arson.", "npc/overwatch/radiovoice/nonsanctionedarson51.wav");
PLUGIN.voices:AddCombine("Combine", "99", "99, reckless operation.", "npc/overwatch/radiovoice/recklessoperation99.wav");
PLUGIN.voices:AddCombine("Combine", "507", "507, public non-compliance.", "npc/overwatch/radiovoice/publicnoncompliance507.wav");
PLUGIN.voices:AddCombine("Combine", "187", "Suspect is now 187.", "npc/overwatch/radiovoice/suspectisnow187.wav");
PLUGIN.voices:AddCombine("Combine", "In progress", "In progress.", "npc/overwatch/radiovoice/inprogress.wav");
PLUGIN.voices:AddCombine("Combine", "Loyalty check", "Oh I have a failure to comply with loyalty check, tag is possible 10-103m.", "npc/metropolice/vo/loyaltycheckfailure.wav");
PLUGIN.voices:AddCombine("Combine", "Stabilization teams", "Overwatch activate central transport stabilization teams.", "npc/combine_soldier/vo/prison_soldier_activatecentral.wav");
PLUGIN.voices:AddCombine("Combine", "Going", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav");
PLUGIN.voices:AddCombine("Combine", "Look out", "Look out!", "npc/metropolice/vo/lookout.wav");
PLUGIN.voices:AddCombine("Combine", "Any help", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav");
PLUGIN.voices:AddCombine("Combine", "Get in", "Get in.", "vo/trainyard/ba_getin.wav");
PLUGIN.voices:AddCombine("Combine", "Get in here", "Get in here.", "vo/trainyard/ba_inhere01.wav");
PLUGIN.voices:AddCombine("Combine", "Come citizen", "You, citizen, come with me.", "vo/trainyard/ba_youcomewith.wav");
PLUGIN.voices:AddCombine("Combine", "Go on", "Go on.", "vo/trainyard/ba_goon.wav");
PLUGIN.voices:AddCombine("Combine", "No im good", "No, I'm good.", "vo/trainyard/ba_noimgood.wav");
PLUGIN.voices:AddCombine("Combine", "Back up", "Back up.", "vo/trainyard/ba_backup.wav");
PLUGIN.voices:AddCombine("Combine", "I said move", "I said move!", "vo/trainyard/ba_move01.wav");
PLUGIN.voices:AddCombine("Combine", "1", "One.", "npc/combine_soldier/vo/one.wav");
PLUGIN.voices:AddCombine("Combine", "2", "Two.", "npc/combine_soldier/vo/two.wav");
PLUGIN.voices:AddCombine("Combine", "3", "Three.", "npc/combine_soldier/vo/three.wav");
PLUGIN.voices:AddCombine("Combine", "4", "Four.", "npc/combine_soldier/vo/four.wav");
PLUGIN.voices:AddCombine("Combine", "5", "Five.", "npc/combine_soldier/vo/five.wav");
PLUGIN.voices:AddCombine("Combine", "6", "Six.", "npc/combine_soldier/vo/six.wav");
PLUGIN.voices:AddCombine("Combine", "7", "Seven.", "npc/combine_soldier/vo/seven.wav");
PLUGIN.voices:AddCombine("Combine", "8", "Eight.", "npc/combine_soldier/vo/eight.wav");
PLUGIN.voices:AddCombine("Combine", "9", "Nine.", "npc/metropolice/vo/nine.wav");
PLUGIN.voices:AddCombine("Combine", "9", "Niner.", "npc/combine_soldier/vo/niner.wav");
PLUGIN.voices:AddCombine("Combine", "10", "Ten.", "npc/metropolice/vo/ten.wav");
PLUGIN.voices:AddCombine("Combine", "20", "Twenty.", "npc/metropolice/vo/twenty.wav");
PLUGIN.voices:AddCombine("Combine", "30", "Thirty.", "npc/metropolice/vo/thirty.wav");
PLUGIN.voices:AddCombine("Combine", "40", "Fourty.", "npc/metropolice/vo/fourty.wav");
PLUGIN.voices:AddCombine("Combine", "50", "Fifty.", "npc/metropolice/vo/fifty.wav");
PLUGIN.voices:AddCombine("Combine", "Line", "Line.", "npc/metropolice/vo/line.wav");
PLUGIN.voices:AddCombine("Combine", "Grenade", "Grenade!", "npc/metropolice/vo/grenade.wav");
PLUGIN.voices:AddCombine("Combine", "Hold", "Hold it.", "npc/metropolice/vo/holdit.wav");
PLUGIN.voices:AddCombine("Combine", "Position", "Protection team, hold this position.", "npc/metropolice/vo/holdthisposition.wav");
PLUGIN.voices:AddCombine("Combine", "Down", "Is down!", "npc/metropolice/vo/isdown.wav");
PLUGIN.voices:AddCombine("Combine", "Activate Central", "Overwatch activate central transport stabilization teams.", "npc/combine_soldier/vo/prison_soldier_activatecentral.wav");
PLUGIN.voices:AddCombine("Combine", "Boomers inbound", "Overwatch confirm status, boomers inbound, prepare for special supression and report.", "npc/combine_soldier/vo/prison_soldier_boomersinbound.wav");
PLUGIN.voices:AddCombine("Combine", "On Visual", "Acquiring on visual.", "npc/metropolice/vo/acquiringonvisual.wav");
PLUGIN.voices:AddCombine("Combine", "Affirmative 2", "Affirmative.", "npc/metropolice/vo/affirmative2.wav");
PLUGIN.voices:AddCombine("Combine", "BOL", "All Units, BOL, We have Thirty Four's At...", "npc/metropolice/vo/allunitsbol34sat.wav");
PLUGIN.voices:AddCombine("Combine", "Code2", "All units, Code two.", "npc/metropolice/vo/allunitscode2.wav");
PLUGIN.voices:AddCombine("Combine", "Pickup 647e", "Anyone pickup uhh..647e reading?", "npc/metropolice/vo/anyonepickup647e.wav");
PLUGIN.voices:AddCombine("Combine", "Back me up", "Back me up, I'm out!.", "npc/metropolice/vo/backmeupImout.wav");
PLUGIN.voices:AddCombine("Combine", "Break Cover", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav");
PLUGIN.voices:AddCombine("Combine", "No 647", "Clear, no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav");
PLUGIN.voices:AddCombine("Combine", "Dead Body", "Dead body Count is...", "npc/metropolice/vo/dbcountis.wav");
PLUGIN.voices:AddCombine("Combine", "Deserviced Area", "Deserviced Area.", "npc/metropolice/vo/deservicedarea.wav");
PLUGIN.voices:AddCombine("Combine", "Establish Perimiter", "CP We need to establish perimiter at...", "npc/metropolice/vo/cpweneedtoestablishperimiterat.wav");
PLUGIN.voices:AddCombine("Combine", "3", "Three.", "npc/metropolice/vo/three.wav");
PLUGIN.voices:AddCombine("Combine", "Check miscount", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav");
PLUGIN.voices:AddCombine("Combine", "Airwatch 243", "CP we need Airwatch to BOL for that 243.", "npc/metropolice/vo/checkformiscount.wav");
PLUGIN.voices:AddCombine("Combine", "10-14", "Holding, I'm at 10-14 Duty at code four.", "npc/metropolice/vo/holdingon10-14duty.wav");
PLUGIN.voices:AddCombine("Combine", "Bugs loose", "We got bugs on the loose.", "npc/metropolice/vo/bugsontheloose.wav");
PLUGIN.voices:AddCombine("Combine", "Is Passive", "Is Passive.", "npc/metropolice/vo/ispassive.wav");
PLUGIN.voices:AddCombine("Combine", "Move along.", "Move along.", "npc/metropolice/vo/movealong.wav");
PLUGIN.voices:AddCombine("Combine", "Move it 2", "Move it!", "npc/metropolice/vo/moveit.wav");
PLUGIN.voices:AddCombine("Combine", "3", "Three.", "npc/metropolice/vo/three.wav");
PLUGIN.voices:AddCombine("Combine", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav");
PLUGIN.voices:AddCombine("Combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav");
PLUGIN.voices:AddCombine("Combine", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav");
PLUGIN.voices:AddCombine("Combine", "10-65", "Unit is 10-65.", "npc/metropolice/vo/ten97.wav");
PLUGIN.voices:AddCombine("Combine", "heis", "There he is!", "npc/metropolice/vo/thereheis.wav");
PLUGIN.voices:AddCombine("Combine", "10-97 goa", "10-97, the suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav");
PLUGIN.voices:AddCombine("Combine", "Hunting", "10-0, 10-0, viscerator is hunting.", "npc/metropolice/vo/tenzerovisceratorishunting.wav");
PLUGIN.voices:AddCombine("Combine", "10-99", "Officer down I am 10-99! Repeat I am 10-99!", "npc/metropolice/vo/officerdowniam10-99.wav");
PLUGIN.voices:AddCombine("Combine", "Responding", "Responding.", "npc/metropolice/vo/responding2.wav");
PLUGIN.voices:AddCombine("Combine", "Contact Suspect", "Contact with 243 suspect. My 10-20 is..", "npc/metropolice/vo/contactwith243suspect.wav");
PLUGIN.voices:AddCombine("Combine", "Roller", "Roller.", "npc/metropolice/vo/roller.wav");
PLUGIN.voices:AddCombine("Combine", "Take down", "Take him down!", "npc/metropolice/takedown.wav");
PLUGIN.voices:AddCombine("Combine", "11-44", "Get that 11-44 inbound, we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav");
PLUGIN.voices:AddCombine("Combine", "Sacrifice code 1", "All units sacrifice code 1 and maintain this CP.", "npc/metropolice/vo/sacrificecode1maintaincp.wav");
PLUGIN.voices:AddCombine("Combine", "Serve", "Serve.", "npc/metropolice/vo/serve.wav");
PLUGIN.voices:AddCombine("Combine", "Stick", "Stick.", "npc/metropolice/vo/stick.wav");
PLUGIN.voices:AddCombine("Combine", "Suspect 11-6", "Suspect 11-6 my 10-20 is..", "npc/metropolice/vo/suspect11-6my1020is.wav");
PLUGIN.voices:AddCombine("Combine", "Victor", "Victor!", "npc/metropolice/vo/victor.wav");
PLUGIN.voices:AddCombine("Combine", "Non Tagged viromes", "Non tagged viromes here.", "npc/metropolice/vo/nontaggedviromeshere.wav");
PLUGIN.voices:AddCombine("Combine", "Officer under fire", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav");
PLUGIN.voices:AddCombine("Combine", "Quick", "Quick!", "npc/metropolice/vo/quick.wav");
PLUGIN.voices:AddCombine("Combine", "Got him again", "Got him again. Suspect is 10-20 at..", "npc/metropolice/vo/gothimagainsuspect10-20at.wav");
PLUGIN.voices:AddCombine("Combine", "Accomplice", "I got 1 accomplice here.", "npc/metropolice/vo/gotoneaccomplicehere.wav");
PLUGIN.voices:AddCombine("Combine", "Code 100", "Code 100.","npc/metropolice/vo/code100.wav");
PLUGIN.voices:AddCombine("Combine", "Teamdown", "Overwatch team is down this sector is not controlled!","npc/combine_soldier/vo/overwatchteamisdown.wav");
PLUGIN.voices:AddCombine("Combine", "Reinforcement", "Overwatch request reinforcement.","npc/combine_soldier/vo/overwatchrequestreinforcement.wav");
PLUGIN.voices:AddCombine("Combine", "10-78", "Dispatch I need 10-78, officer in trouble!","npc/metropolice/vo/dispatchIneed10-78.wav");
PLUGIN.voices:AddCombine("Combine", "Close Suspect", "All Units! Close on Suspect!","npc/metropolice/vo/allunitscloseonsuspect.wav");
PLUGIN.voices:AddCombine("Combine", "Ready weapons", "Ready weapons, possible hostiles inbound.","npc/combine_soldier/vo/readyweaponshostilesinbound.wav");
PLUGIN.voices:AddCombine("Combine", "Charges", "Ready charges!","npc/combine_soldier/vo/readycharges.wav");
PLUGIN.voices:AddCombine("Combine", "Sector Secured", "Sector is Secured, mo viscon.","npc/combine_soldier/vo/sectorissecurenovison.wav");
PLUGIN.voices:AddCombine("Combine", "Confirmed", "Contact Confirmed, Prosecuting!","npc/combine_soldier/vo/contactconfirmprosecuting.wav");
PLUGIN.voices:AddCombine("Combine", "Stabilization", "Stabilization team holding in position.","npc/combine_soldier/vo/stabilizationteamholding.wav");
PLUGIN.voices:AddCombine("Combine", "Compromised", "Target compromised, move in! move in!","npc/combine_soldier/vo/targetcompromisedmovein.wav");
PLUGIN.voices:AddCombine("Combine", "Infestation", "We are in an infestation zone.","npc/combine_soldier/vo/weareinaninfestationzone.wav");
PLUGIN.voices:AddCombine("Combine", "Medical", "Request Medical!","npc/combine_soldier/vo/requestmedical.wav");
PLUGIN.voices:AddCombine("Combine", "Stay alert", "Stay alert, report sight lines.","npc/combine_soldier/vo/stayalertreportsightlines.wav");
PLUGIN.voices:AddCombine("Combine", "Positions", "All units move to arrest positions.","npc/metropolice/vo/movetoarrestpositions.wav");
PLUGIN.voices:AddCombine("Combine", "Pacifying", "Pacifying!","npc/metropolice/vo/pacifying.wav");
PLUGIN.voices:AddCombine("Combine", "10-15", "Prepare for 10-15","npc/metropolice/vo/preparefor1015.wav");
PLUGIN.voices:AddCombine("Combine", "Prosecute Final", "Ready to prosecute malcompliant citizen final warning issued!","npc/metropolice/vo/readytoprosecutefinalwarning.wav");
PLUGIN.voices:AddCombine("Combine", "10-108", "We have a 10-108!","npc/metropolice/vo/wehavea10-108.wav");
PLUGIN.voices:AddCombine("Combine", "10-8", "Unit is on duty, 10-8.","npc/metropolice/vo/unitisonduty10-8.wav");
PLUGIN.voices:AddCombine("Combine", "Clearcode100", "Clear and code 100.","npc/metropolice/vo/clearandcode100.wav");
PLUGIN.voices:AddCombine("Combine", "Still 647e", "Still getting a 647e from local surveillance.","npc/metropolice/vo/stillgetting647e.wav");
PLUGIN.voices:AddCombine("Combine", "Blip", "Catch that blip on the stabilization readout?","npc/metropolice/vo/catchthatbliponstabilization.wav");
PLUGIN.voices:AddCombine("Combine", "Ripcord", "Ripcord.","npc/combine_soldier/vo/ripcord.wav");
PLUGIN.voices:AddCombine("Combine", "Ripcord 2", "Ripcord, ripcord!","npc/combine_soldier/vo/ripcordripcord.wav");
PLUGIN.voices:AddCombine("Combine", "Condemned", "Condemned zone.", "npc/metropolice/vo/condemnedzone.wav");
PLUGIN.voices:AddCombine("Combine", "Confirm Priority", "Confirm priority 1 sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav");
PLUGIN.voices:AddCombine("Combine", "Converging", "Converging.", "npc/metropolice/vo/converging.wav");
PLUGIN.voices:AddCombine("Combine", "CP Compromised", "CP is compromised. Reestablish!", "npc/metropolice/vo/cpiscompromised.wav");
PLUGIN.voices:AddCombine("Combine", "Overrun", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav");
PLUGIN.voices:AddCombine("Combine", "CP report in", "CP requests all units..uh..location report in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav");
PLUGIN.voices:AddCombine("Combine", "Designate", "Designate suspect as..", "npc/metropolice/vo/designatesuspectas.wav");
PLUGIN.voices:AddCombine("Combine", "Dismounting", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav");
PLUGIN.voices:AddCombine("Combine", "Disp Report", "Disp reports, suspect incursion at location.", "npc/metropolice/vo/dispreportssuspectincursion.wav");
PLUGIN.voices:AddCombine("Combine", "Disp Updating", "Disp updating APB likeness.", "npc/metropolice/vo/dispupdatingapb.wav");
PLUGIN.voices:AddCombine("Combine", "Distribution", "Distribution block.", "npc/metropolice/vo/distributionblock.wav");
PLUGIN.voices:AddCombine("Combine", "Hardpoint Scanning", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav");
PLUGIN.voices:AddCombine("Combine", "Hes 148", "He's gone 148!", "npc/metropolice/vo/hesgone148.wav");
PLUGIN.voices:AddCombine("Combine", "Up there", "He's up there!", "npc/metropolice/vo/hesupthere.wav");
PLUGIN.voices:AddCombine("Combine", "Hiding last", "Hiding, last seen at range..", "npc/metropolice/vo/hidinglastseenatrange.wav");
PLUGIN.voices:AddCombine("Combine", "High Priority", "High priority region.", "npc/metropolice/vo/highpriorityregion.wav");
PLUGIN.voices:AddCombine("Combine", "Industrial", "Industrial zone.", "npc/metropolice/vo/industrialzone.wav");
PLUGIN.voices:AddCombine("Combine", "Infested", "Infested zone.", "npc/metropolice/vo/infestedzone.wav");
PLUGIN.voices:AddCombine("Combine", "In position at", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav");
PLUGIN.voices:AddCombine("Combine", "In position 1", "In position on 1 ready.", "npc/metropolice/vo/inpositionononeready.wav");
PLUGIN.voices:AddCombine("Combine", "At hardpoint", "Is at hardpoint, ready to prosecute.", "npc/metropolice/vo/isathardpointreadytoprosecute.wav");
PLUGIN.voices:AddCombine("Combine", "Is closing", "Is closing on suspect!", "npc/metropolice/vo/isclosingonsuspect.wav");
PLUGIN.voices:AddCombine("Combine", "Proceed", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav");
PLUGIN.voices:AddCombine("Combine", "At location", "Protect teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav");
PLUGIN.voices:AddCombine("Combine", "Go again", "PT go again.", "npc/metropolice/vo/ptgoagain.wav");
PLUGIN.voices:AddCombine("Combine", "Code3", "Reinforcement teams, code 3!", "npc/metropolice/vo/reinforcementteamscode3.wav");
PLUGIN.voices:AddCombine("Combine", "Report Sights", "Report sightings of possible accomplice.", "npc/metropolice/vo/reportsightingsaccomplices.wav");
PLUGIN.voices:AddCombine("Combine", "Repurposed", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav");
PLUGIN.voices:AddCombine("Combine", "Low on", "Running low on veridcts, taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav");
PLUGIN.voices:AddCombine("Combine", "Shots fired", "Shots fired, hostile malignants here.", "npc/metropolice/vo/shotsfiredhostilemalignants.wav");
PLUGIN.voices:AddCombine("Combine", "Jurisdiction", "Stabilization jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav");
PLUGIN.voices:AddCombine("Combine", "High speed", "All units be advised, subject is now high speed.", "npc/metropolice/vo/subjectisnowhighspeed.wav");
PLUGIN.voices:AddCombine("Combine", "10-91", "10-91d count is..", "npc/metropolice/vo/ten91dcountis.wav");
PLUGIN.voices:AddCombine("Combine", "UTL", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav");
PLUGIN.voices:AddCombine("Combine", "UTL that", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav");
PLUGIN.voices:AddCombine("Combine", "Stable at", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav");
PLUGIN.voices:AddCombine("Combine", "DB Here", "Uhh...we got a DB here, cancel that 11-42.", "npc/metropolice/vo/wegotadbherecancel10-102.wav");
PLUGIN.voices:AddCombine("Combine", "Preparing", "Preparing to judge a 10-107, be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav");
PLUGIN.voices:AddCombine("Combine", "Possible 647", "Possible 647e here, request Airwatch tag.", "npc/metropolice/vo/possible647erequestairwatch.wav");
PLUGIN.voices:AddCombine("Combine", "Possible 10-103", "Possible 10-103, my location, alert tag units.", "npc/metropolice/vo/possible10-103alerttagunits.wav");
PLUGIN.voices:AddCombine("Combine", "Position to", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav");
PLUGIN.voices:AddCombine("Combine", "Outland Biotic", "I got an outland biotic in here.", "npc/metropolice/vo/outlandbioticinhere.wav");
PLUGIN.voices:AddCombine("Combine", "Non Patrol", "Non patrol region.", "npc/metropolice/vo/nonpatrolregion.wav");
PLUGIN.voices:AddCombine("Combine", "Non Citizen", "Non citizen.", "npc/metropolice/vo/noncitizen.wav");
PLUGIN.voices:AddCombine("Combine", "No contact", "No contact.", "npc/metropolice/vo/nocontact.wav");
PLUGIN.voices:AddCombine("Combine", "Hardpoint 2", "Moving to hardpoint!", "npc/metropolice/vo/movingtohardpoint2.wav");
PLUGIN.voices:AddCombine("Combine", "Match on", "I have a match on APB likeness.", "npc/metropolice/vo/matchonapblikeness.wav");
PLUGIN.voices:AddCombine("Combine", "408", "I've got a 408 here at location.", "npc/metropolice/vo/Ivegot408hereatlocation.wav");
PLUGIN.voices:AddCombine("Combine", "10-30", "I have a 10-30, my 10-20, responding code 2.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav");
PLUGIN.voices:AddCombine("Combine", "Hiding Range", "Hiding, last seen at range..", "npc/metropolice/vo/hidinglastseenatrange.wav");
PLUGIN.voices:AddCombine("Combine", "10-107 here", "I have a 10-107 here, send Airwatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav");
PLUGIN.voices:AddCombine("Combine", "Firing ", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav");
PLUGIN.voices:AddCombine("Combine", "Unit deserviced", "Unit deserviced.", "npc/overwatch/radiovoice/unitdeserviced.wav");
PLUGIN.voices:AddCombine("Combine", "Down at", "Unit down at..", "npc/overwatch/radiovoice/unitdownat.wav");
PLUGIN.voices:AddCombine("Combine", "Verdict is", "Suspect is judged malignant. Verdict code is..", "npc/overwatch/radiovoice/suspectmalignantverdictcodeis.wav");
PLUGIN.voices:AddCombine("Combine", "Fracture", "Social fracture in progress. Respond.", "npc/overwatch/radiovoice/socialfractureinprogress.wav");
PLUGIN.voices:AddCombine("Combine", "148", "148. Resisting arrest.", "npc/overwatch/radiovoice/resistingpacification148.wav");
PLUGIN.voices:AddCombine("Combine", "Recalibrate", "Team, recalibrate socio-scan.", "npc/overwatch/radiovoice/recalibratesocioscan.wav");
PLUGIN.voices:AddCombine("Combine", "Premature", "Premature mission termination will result in..", "npc/overwatch/radiovoice/prematuremissiontermination.wav");
PLUGIN.voices:AddCombine("Combine", "Lock down", "Protection team, lock down your location. Sacrifice code..", "npc/overwatch/radiovoice/lockdownlocationsacrificecode.wav");
PLUGIN.voices:AddCombine("Combine", "Leaders", "Attention stabilization team leaders: Report deserviced units to sterilized body count ratios for reinforcement reward or removal processing.", "npc/overwatch/radiovoice/leadersreportratios.wav");
PLUGIN.voices:AddCombine("Combine", "Reproduction", "50% reproduction credits.", "npc/overwatch/radiovoice/halfreproductioncredits.wav");
PLUGIN.voices:AddCombine("Combine", "Treat", "Stabilization team: Failure to treat identified local outbreak will foreseen recall and recycle.", "npc/overwatch/radiovoice/failuretotreatoutbreak.wav");
PLUGIN.voices:AddCombine("Combine", "Populcate", "Disassociation from the civic populace.", "npc/overwatch/radiovoice/disassociationfromcivic.wav");
PLUGIN.voices:AddCombine("Combine", "Destruction", "Destruction of corporal social protection units.", "npc/overwatch/radiovoice/destructionofcpt.wav");
PLUGIN.voices:AddCombine("Combine", "Verdict code is", "All units: Verdict code is..", "npc/overwatch/radiovoice/allunitsverdictcodeis.wav");
PLUGIN.voices:AddCombine("Combine", "Terminal", "All units deliver terminal verdict immediately.", "npc/overwatch/radiovoice/allunitsdeliverterminalverdict.wav");
PLUGIN.voices:AddCombine("Combine", "All teams", "All teams respond code 3.", "npc/overwatch/radiovoice/allteamsrespondcode3.wav");
PLUGIN.voices:AddCombine("Combine", "Possible miscount", "Airwatch reports possible miscount.", "npc/overwatch/radiovoice/airwatchreportspossiblemiscount.wav");
PLUGIN.voices:AddCombine("Combine", "No activity", "Airwatch copies no activity.", "npc/overwatch/radiovoice/airwatchcopiesnoactivity.wav");
PLUGIN.voices:AddCombine("Combine", "Accomplices", "Protection team, be advised: Accomplices operating in area.", "npc/overwatch/radiovoice/accomplicesoperating.wav");
PLUGIN.voices:AddCombine("Combine", "Failure to", "Failure to comply with the civil will.", "npc/overwatch/radiovoice/failuretocomply.wav");
PLUGIN.voices:AddCombine("Combine", "OffWorld", "Permanent off-world service assignment.", "npc/overwatch/radiovoice/permanentoffworld.wav");
PLUGIN.voices:AddCombine("Combine", "Visual", "Attention: Prepare visual download of anti-citizen one.", "npc/overwatch/radiovoice/preparevisualdownload.wav");
PLUGIN.voices:AddCombine("Combine", "100 credits", "Rank leader, reminder: 100 sterilized credits qualifies non-mechanical reproduction simulation.", "npc/overwatch/radiovoice/reminder100credits.wav");
PLUGIN.voices:AddCombine("Combine", "Replacement", "Reminder: Memory replacement is the first step towards rank privileges.", "npc/overwatch/radiovoice/remindermemoryreplacement.wav");
PLUGIN.voices:AddCombine("Combine", "Incursion", "Restricted incursion in progress.", "npc/overwatch/radiovoice/restrictedincursioninprogress.wav");
PLUGIN.voices:AddCombine("Combine", "Reward Notice", "Reward notice, protection team member: Your family cohesion is preserved.", "npc/overwatch/radiovoice/rewardnotice.wav");
PLUGIN.voices:AddCombine("Combine", "Suspend", "Suspend negotiations.", "npc/overwatch/radiovoice/suspendnegotiations.wav");
PLUGIN.voices:AddCombine("Combine", "Are Charged", "You are charged with terminal violation 148, 243, 245.", "npc/overwatch/radiovoice/youarechargedwithterminal.wav");
PLUGIN.voices:AddCombine("Combine", "Report on", "Local protection team units, report on..", "npc/overwatch/radiovoice/reporton.wav");

if (CLIENT) then
	table.sort(PLUGIN.voices.stored.combineVoices, function(a, b) return a.command < b.command; end);
	
	for k, v in pairs(PLUGIN.voices.stored.combineVoices) do
		Clockwork.directory:AddCode("Combine", [[
			<div class="auraInfoTitle">]]..string.upper(v.command)..[[</div>
			<div class="auraInfoText">]]..v.phrase..[[</div>
		]], true);
	end;
end;